---
language: python
dist: focal
python:
  - 3.8

matrix:
  include:
    - name: Mac OS X 10.15.7
      os: osx
      osx_image: xcode12.2
      language: shell
      before_install:
        - python --version
        - pip3 install ansible
    - name: Windows 10
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python --version
        - pip3 install ansible
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

before_install:
  - python3 --version
  - pip3 install ansible

script:
  - ansible --version
  - printf '[defaults]\nroles_path=../' > ansible.cfg
  - ansible-playbook tests/test.yml -i tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
