---
language: python
os: linux
python: "3.8"

install:
  - python3 -m pip install molecule[docker]

script:
  - molecule --version
  - ansible --version

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
