---
- name: Ensure snapd is installed
  apt:
    name: snapd
    state: present
    update_cache: true

- name: Ensure snap core is installed
  community.general.snap:
    name: core
    state: present
